# Generated by Django 2.2 on 2019-05-05 15:55

from django.db import migrations, models
import server.utils.storage


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20190505_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(upload_to=server.utils.storage.decide_save_location),
        ),
    ]
