# Generated by Django 2.2 on 2019-05-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_classifiercreationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Detection',
        ),
    ]
