# Generated by Django 2.2.1 on 2019-05-11 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_auto_20190507_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detection',
            name='camera',
        ),
    ]
