# Generated by Django 2.2 on 2019-05-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_detection_image_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='save_locataion',
            field=models.CharField(default='/', max_length=1000),
        ),
        migrations.AlterField(
            model_name='detection',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(upload_to=models.CharField(default='/', max_length=1000)),
        ),
    ]
