# Generated by Django 2.2 on 2019-05-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20190505_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='save_location',
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(upload_to=None),
        ),
    ]
