# Generated by Django 2.2 on 2019-05-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20190505_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifierCreationDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
