# Generated by Django 2.2 on 2019-05-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_detection'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
