# Generated by Django 2.2.1 on 2019-05-13 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_auto_20190513_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='downscale_level',
            field=models.FloatField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
