# Generated by Django 2.2.1 on 2019-05-20 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0019_auto_20190520_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.City'),
        ),
    ]
